services:
  - type: web
    name: litestart-backend
    env: node
    plan: free
    buildCommand: cd backend && npm install
    startCommand: cd backend && npm start
    envVars:
      - key: MONGO_URI
        value: mongodb+srv://Project-Scott-Reece:InternBES25@project.q0lhe0r.mongodb.net/project1?retryWrites=true&w=majority&appName=Project
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000 